name: Main Actions
on:
  push:
    branches:
      - main
jobs:
  test-package:
    name: Test and Package Main Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Ensure pip is latest version
        run: python -m pip install --upgrade pip
      - name: Install pipenv
        run: python -m pip install pipenv
      - name: Setup pipenv virtual environment (and project dependencies)
        run: pipenv install
      - name: Run unit tests
        run: pipenv run ./run-tests.sh
      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Results
          path: test_results.xml
          reporter: java-junit
      - name: Coverage Report
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 75
          report_name: Coverage Report
      - name: Build wheel (but don't release)
        run: pipenv run python setup.py sdist bdist_wheel
      - name: Tag release
        run: |
          VERSION=v$(cat pyproject.toml | grep version | awk -F'"' '{print $2}')
          git tag $VERSION
          git push origin $VERSION
      - name: Retrieve dev branch
        run: |
          git fetch origin
          git checkout dev
          git pull --rebase
      - name: Bump dev branch to next version
        id: version
        uses: vemel/nextversion@main
        with:
          path: ./pyproject.toml
          type: pep440
          result: micro
          release: stable
          update: ./pyproject.toml
      - name: Commit updated version file
        run: |
          VERSION=${{ toJSON(steps.version.outputs.result) }}
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Bump dev branch version to $VERSION"
          git push --set-upstream origin dev
