name: Release Actions
on:
  push:
    tags:
      - 'v*'
jobs:
  test-package-release:
    name: Test and Deploy Production Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Ensure pip is latest version
        run: python -m pip install --upgrade pip
      - name: Install pipenv
        run: python -m pip install pipenv
      - name: Setup pipenv virtual environment (and project dependencies)
        run: pipenv install
      - name: Run unit tests
        run: pipenv run ./run-tests.sh
      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Results
          path: test_results.xml
          reporter: java-junit
      - name: Coverage Report
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 75
          report_name: Coverage Report
      - name: Build wheel
        run: pipenv run python setup.py sdist bdist_wheel
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: dist/*
      - name: Publish to PyPi (production)
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PROD_TOKEN }}
          TWINE_NON_INTERACTIVE: 1
        run: pipenv run twine upload --skip-existing dist/*
